version: '3'

services:
  frontend:
    build: ./pizzeria-front
    ports:
      - "3000:3000"
      
  backend:
    build: ./pizzeria-api/PizzeriaApi
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Pizzeria=Server=database,1433;Database=Pizzeria;Integrated Security=True;
  
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "MyStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./db_scripts:/usr/src/app/db_scripts
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"
